spring:
  application:
    name: AnsimTouch-server

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 3600000
  refresh-token-expire-time: 604800000

coolsms:
  api:
    key: ${COOLSMS_KEY}
    secret: ${COOLSMS_SECRET}
  fromnumber: ${COOLSMS_FROMNUMBER}