spring:
  application:
    name: AnsimTouch-server

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
    mongodb:
      uri: ${MONGODB_URL}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      api-url: ${OPENAI_API_URL}
      assistantId: ${OPENAI_ASSISTANT_ID}

  cloud:
    function:
      enabled: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 3600000
  refresh-token-expire-time: 604800000

map:
  api:
    key: ${KAKAO_MAP_API}

coolsms:
  api:
    key: ${COOLSMS_KEY}
    secret: ${COOLSMS_SECRET}
  fromnumber: ${COOLSMS_FROMNUMBER}

firebase:
  json-key: ${FIREBASE_JSON_KEY}